import { BusinessUnit } from "./types";

export const businessUnits: BusinessUnit[] = [
  {
    id: "seguranca",
    title: "Segurança do Trabalho",
    subtitle: "Conformidade • Gestão • Performance",
    description:
      "Implantação de sistemas de gestão em Segurança do Trabalho, auditorias, inspeções técnicas, cultura organizacional e conformidade legal.",
    href: "/solucoes/seguranca-do-trabalho",
    image: "/images/business/safety.webp",
    icon: "ShieldCheck",
    color: "#0F5C3A",
    services: [
      "Consultoria em SST",
      "Auditorias Técnicas",
      "Fiscalizações",
      "Gestão do PGR",
      "GRO",
      "APR",
      "Inspeções Técnicas",
      "Indicadores de Segurança",
      "Cultura Organizacional",
      "Treinamentos Corporativos",
    ],
  },

  {
    id: "engenharia",
    title: "Engenharia Elétrica",
    subtitle: "Projetos • Confiabilidade • Eficiência",
    description:
      "Projetos elétricos, inspeções, SPDA, aterramento, diagramas unifilares, dimensionamentos e soluções para instalações elétricas.",
    href: "/solucoes/engenharia-eletrica",
    image: "/images/business/engineering.webp",
    icon: "Bolt",
    color: "#145A32",
    services: [
      "Projetos Elétricos",
      "SPDA",
      "Aterramento",
      "Diagramas",
      "Quadros Elétricos",
      "As Built",
      "Estudos de Carga",
      "Dimensionamentos",
      "Eficiência Energética",
      "Inspeções Técnicas",
    ],
  },

  {
    id: "eletrotecnica",
    title: "Eletrotécnica",
    subtitle: "Execução • Instalação • Manutenção",
    description:
      "Serviços técnicos especializados em instalações elétricas, manutenção preventiva, corretiva, retrofit e modernização de sistemas.",
    href: "/solucoes/eletrotecnica",
    image: "/images/business/electrical.webp",
    icon: "Wrench",
    color: "#196F3D",
    services: [
      "Instalações Elétricas",
      "Manutenção Preventiva",
      "Manutenção Corretiva",
      "Retrofit",
      "Painéis Elétricos",
      "Comandos",
      "Infraestrutura",
      "Montagem Industrial",
      "Diagnóstico de Falhas",
      "Comissionamento",
    ],
  },

  {
    id: "automacao",
    title: "Automação Industrial",
    subtitle: "CLP • Supervisão • Controle",
    description:
      "Automação de processos industriais utilizando tecnologias modernas para aumentar produtividade, segurança e eficiência operacional.",
    href: "/solucoes/automacao-industrial",
    image: "/images/business/automation.webp",
    icon: "Cpu",
    color: "#1E8449",
    services: [
      "CLP",
      "IHM",
      "Painéis",
      "Sensores",
      "Integração",
      "Retrofit",
      "Supervisórios",
      "Programação",
      "Controle Industrial",
      "Diagnóstico",
    ],
  },

  {
    id: "pericias",
    title: "Perícias Técnicas",
    subtitle: "Análise • Investigação • Evidências",
    description:
      "Assistência técnica especializada, perícias judiciais e extrajudiciais, investigações técnicas e emissão de pareceres.",
    href: "/solucoes/pericias",
    image: "/images/business/expert.webp",
    icon: "Search",
    color: "#21618C",
    services: [
      "Perícias Técnicas",
      "Assistência Judicial",
      "Parecer Técnico",
      "Investigação de Acidentes",
      "Análise de Falhas",
      "Vistorias",
      "Inspeções",
      "Laudos",
      "Consultoria Pericial",
      "Evidências Técnicas",
    ],
  },

  {
    id: "bombeiro",
    title: "Bombeiro Civil",
    subtitle: "Prevenção • Emergência • Resposta",
    description:
      "Planejamento preventivo, inspeções, brigadas, simulados e treinamentos voltados à proteção de vidas e patrimônio.",
    href: "/solucoes/bombeiro-civil",
    image: "/images/business/fire.webp",
    icon: "Flame",
    color: "#0B5345",
    services: [
      "Brigada de Incêndio",
      "NR-23",
      "Plano de Emergência",
      "Simulados",
      "Rotas de Fuga",
      "Extintores",
      "Hidrantes",
      "Inspeções",
      "Treinamentos",
      "Prevenção",
    ],
  },

  {
    id: "analytics",
    title: "Business Intelligence",
    subtitle: "Dados • Indicadores • Inteligência",
    description:
      "Transformação de dados em decisões estratégicas através de dashboards, indicadores de desempenho e inteligência aplicada.",
    href: "/solucoes/business-intelligence",
    image: "/images/business/analytics.webp",
    icon: "LineChart",
    color: "#117864",
    services: [
      "Dashboards",
      "Power BI",
      "KPIs",
      "Indicadores",
      "Analytics",
      "Business Intelligence",
      "Relatórios Gerenciais",
      "Automação de Dados",
      "Performance",
      "IA Aplicada",
    ],
  },

  {
    id: "academy",
    title: "MERIDIUM Academy",
    subtitle: "Treinamentos • Capacitação • Desenvolvimento",
    description:
      "Capacitação técnica corporativa com foco em desenvolvimento profissional, segurança operacional e excelência organizacional.",
    href: "/academy",
    image: "/images/business/academy.webp",
    icon: "GraduationCap",
    color: "#145A32",
    services: [
      "NR-01",
      "NR-05",
      "NR-06",
      "NR-10",
      "NR-11",
      "NR-12",
      "NR-18",
      "NR-20",
      "NR-23",
      "NR-33",
      "NR-35",
      "Cursos In Company",
    ],
  },
];
